[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"

[build]
  command = "npm run production"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
    from = "/uses"
    to = "/notes/my-uses-page/"
    status = 301
    force = false
